### PR TITLE
Add AGENDA for 2020-02-27

### PR DESCRIPTION
**Pull request by reszelaz**
Hi,
This is the provisional agenda for tomorrow's meeting. Please comment and propose topics to be discussed. I plan to send it to the sardana-devel mailing list late this afternoon.

@daneos do you plan to submit the minutes from the previous meeting? I wanted to add the pending task to be reviewed tomorrow. 

Just to confirm, tomorrow we meet: @teresanunez from DESY, @julianofjm and @aureocarneiro from MAXIV, @daneos from SOLARIS and @reszelaz from ALBA, right?

Cheers,
Zibi

### CODE REVIEW

**Review by teresanunez — APPROVED** [review]

**Comment by teresanunez** [comment]
@reszelaz, I will meet. Thanks.

**Comment by daneos** [comment]
Yes, I plan to submit the minutes, I just didn't have time for that. I'll update the agenda with tasks from the previous meeting.
Since there's still no one at SOLARIS to take over from me I guess I'll be present on the meeting.

**Review by daneos — APPROVED** [review]

**Comment by daneos** [comment]
It turns out I won't be able to participate today. Sorry for inconvenience!

**Comment by reszelaz** [comment]
> It turns out I won't be able to participate today. Sorry for inconvenience!

Thanks for letting us know! Cheers!

**Pull request merged**
