### PR TITLE
Agenda dec18

### PR DESCRIPTION
**Pull request by teresanunez**

### CODE REVIEW

**Comment by reszelaz** [comment]
Thanks @teresanunez for preparing the meeting!
Regarding the agenda, we could also comment on the [Automation in Beamline Control and Data Acquisition Workshop](https://www.helmholtz-berlin.de/events/automation). There will be a slot to present Sardana.
And maybe we could try the Jitsi tool this time. Recently we used it with @amilan and it worked quite well. As a fallback we could always use the appear.in.

**Comment by teresanunez** [comment]
Hi @reszelaz, thanks, I have added the point you mention. Yes, of course, we can use Jitsi.

**Comment by reszelaz** [comment]
I also think it is a good moment to review the Jan18 milestone and maybe drop or include some issues. What do you think?

Since the agenda is getting more and more tight it would be great if you could read SEP2 in advance.

**Comment by teresanunez** [comment]
HI @reszelaz, the point about the Jan18 milestones is added. Yes, we have to try to look as much as possible in advance.

**Comment by reszelaz** [comment]
For the jitsi test, I think it will be as easy as entering: https://meet.jit.si/ and opening the "sardana" meeting. The first person will start the meeting, the next ones will just join it. Please remember to use the "sardana" meeting name!

**Pull request merged**
