### PR TITLE
Agenda for 05.04.2018

### PR DESCRIPTION
**Pull request by daneos**
Here's the agenda for the upcoming meeting.
I hoped to do a presentation about some of Solaris custom macros, but I probably won't have time to prepare it, so maybe during the next meeting?
Please check and add your ideas.

### CODE REVIEW

**Comment by teresanunez** [comment]
The agenda is ok for me. The first point ... as you want, if you don't have time now just postpone it. No problem.

**Comment by amilan** [comment]
Sounds good.
See you on Thursday!

**Comment by reszelaz** [comment]
Great! Don't worry about the presentation. We can exclude it from this meeting and keep it for the next one.

I've written down my ideas about the third-party repositories - see sardana-org/sardana#726 (SEP16). It would be nice if you could dedicate some time to read it before the meeting.

**Comment by reszelaz** [comment]
I advance you two more things that we could discuss in the AOB section:
* Short meeting satellite to the Tango Meeting? If there is interest?
* Sardana project Wiki pages.

**Comment by amilan** [comment]
Nice, I had the same point regarding meetings or workshops during 2018 (including but not limiting only to tango meeting).

**Comment by reszelaz** [comment]
> (including but not limiting only to tango meeting)

Yeap, there is also the NOBUGS conference this year. Let's talk about it tomorrow..

**Comment by teresanunez** [comment]
Hi, there is another point we could discuss tomorrow: the implementation we did of the spock logging,
 it looks like some people prefer the old way I had implemented, with the clear macro in the way it
 was typed in spock and its spock outputs.

**Comment by reszelaz** [comment]
> the implementation we did of the spock logging

Great, let's add it to the agenda.

**Comment by daneos** [comment]
OK, updated agenda.

**Comment by reszelaz** [comment]
Great, I have added a point about a new video conferencing tool. I'm merging the agenda.

**Pull request merged**
