### PR TITLE
Add minutes.

### PR DESCRIPTION
**Pull request by amilan**
Addin minutes from the last meeting, held on 2019/02/14.

### CODE REVIEW

**Comment by amilan** [comment]
Hi,

Here are the minutes from yesterday's meeting. Please review it and add anything that may be missing.

Cheers,
Antonio.

**Comment by teresanunez** [comment]
Hi Antonio, thanks for the minutes. I already corrected a typo and here some comments:

- In point 6 about the Sardana Documentation Camp 2019, actually if it is done at DESY it would
not be more than 3 days, it would start on Wednesday afternoon unti Friday, so maximum two
 and half. You could put that three days was two short and that it could be longer, but this is not
 related to the fact that could be done at DESY ( I would add that would be done just after the
 Tango meeting).

- in point 3, I think the sentence:

 Pop-ups improvements that needed to be a widget in edition mode

  it is not clear, I would not know what does mean.

- In point 2, perhaps one can add a little more information, but I don't know ... the minutes are also not
 inteded to be a documentation, just in case ... one could put something like:
  * Allows single acquisiton of a channel witthout need of the measurement group.
  * Implemented in the so called timerable elements: countertimers, oned and twod. It would
    be extended to zeroD and PseudoCounters.
  * Two new members, timer and integration time, are added to the timerables in the pool core and in
    the Tango interface.
  * The timer and timerable has to be axe of the same controller.
  * Three special values are defined for the Timer:

      * __default: Default timer for the controller in use, defined in the
       controller plugin as a class member. If the element belonging to
       this axis is not defined in the controller, resetting the controller's
       timer to the default one raises an exception.
      * __self: the own channel is its timer.
      * None: disable the single acquisition
   * Timer is a memorized attribute if never set __default.  

 That's all, thanks again @amilan

**Review by reszelaz — APPROVED** [review]
Many thanks @amilan! I really like the idea of actions to be taken with checklist!

I added some suggestions from @teresanunez and made some formatting changes from my side and added link to the slides which I uploaded yesterday to the master branch.

> In point 6 about the Sardana Documentation Camp 2019, actually if it is done at DESY it would
not be more than 3 days, it would start on Wednesday afternoon unti Friday, so maximum two
and half. You could put that three days was two short and that it could be longer, but this is not
related to the fact that could be done at DESY ( I would add that would be done just after the
Tango meeting).

I rephrased the sentence, and I think now it express better the invitation from DESY to stay after the Tango Meeting. Many thanks for this offer! I think that 2 and a half day is also fine. Actually we already know how we want to make the docs, this is what we decided on the last camp. Now is just to write the docs. So we save some time comparing to the last time.

> in point 3, I think the sentence: "Pop-ups improvements that needed to be a widget in edition mode" it is not clear, I would not know what does mean.

I added more details here.

> * In point 2, perhaps one can add a little more information, but I don't know ... the minutes are also not inteded to be a documentation, just in case ... one could put something like [...]

Thanks for all the details Teresa, but I agree with your observation that the minutes are not suppose to be the documentation. This information is already redistributed in the documentation. So I would keep the minutes short.

**Comment by reszelaz** [comment]
Since now we announce the meetings to the sardana-devel mainling list, what do yout hink to reply to the invitation email with the minutes whenever these gets accepted?

If you agree I will add it to the [Meeting Workflow](https://github.com/sardana-org/sardana-followup#meeting-workflow).

**Review by teresanunez — APPROVED** [review]

**Review by daneos — APPROVED** [review]

**Comment by amilan** [comment]
Hi, 

Thanks a lot for completing the minutes!

Regarding sending the minutes as a reply to the invitation ... why not, it could be a nice addition. I'm only afraid if that will be considered too much spam, but as it will be only in the developers list, it may be worth to try.

**Comment by reszelaz** [comment]
OK, I see that it is approved by all 3 of the reviewers I proceed with merge. Thanks @amilan for chairing this one!

**Pull request merged**
