### PR TITLE
First draft. Parts are missed

### PR DESCRIPTION
**Pull request by teresanunez**

### CODE REVIEW

**Comment by reszelaz** [comment]
Thanks @teresanunez !
I just added minutes from the urgent issues part and introduced some minor corrections.
I also uploaded the Sardana Documentation presentation.

For me it can be merged. Well @amilan  presentation is missing but since he is on holidays I would not wait with the merge for this. Afterwards he can push it directly to the master branch.

**Comment by teresanunez** [comment]
HI @reszelaz, many thanks. We can wait until tomorrow, just in case Grezgorz wants to add
 something ... and if not you or me can merge it.

**Comment by reszelaz** [comment]
Perfect!

**Comment by teresanunez** [comment]
I merge it, any further comment can be directly pushed.

**Pull request merged**
