### PR TITLE
Minutes from follow-up meeting held on 02.11.2017

### PR DESCRIPTION
**Pull request by reszelaz**
Participants of the meeting, please comment or edit directly.

### CODE REVIEW

**Review by daneos — APPROVED** [review]
Looks good :)

**Comment by teresanunez** [comment]
It is fine for me. Thanks @reszelaz

**Review by teresanunez — APPROVED** [review]

**Comment by amilan** [comment]
Apart from the non-important typos, the rest looks good. Ready to be merged

**Comment by reszelaz** [comment]
Great! Thanks all of you for your assitance.

**Pull request merged**
