### PR TITLE
Follow-up meeting to be held on 11.12.2017 at 14:00

### PR DESCRIPTION
**Pull request by teresanunez**
This PR is to announce the date of the next follow-up meeting and discusse the agenda.
As in the previous one, the invited people are @reszelaz, @amilan, @daneos and myself.
I propose as general feature to be presented/discussed:

- Spock looging

but no problem if this is postponed to another meeting and we discusse any other feature.

### CODE REVIEW

**Comment by reszelaz** [comment]
Thanks @teresanunez for taking care about the meeting organization!

What do you think to add a point in the agenda to review the status of collaborative development that we have identified in the previous meeting?

**Comment by teresanunez** [comment]
Perfect, I will add it. Thanks.

**Comment by reszelaz** [comment]
I like the idea of presenting the spock logging. @teresanunez, since you are the one who developed it, could you do the presentation? I could add a couple of words about the "report" feature of the MacroServer which is somehow related.

For 2018, at Alba, we are planning to focus on the 2D detectors and Lima integration in Sardana. Do you think that we could dedicate 5 min per each institute to describe our requirements and needs in this area?

**Comment by teresanunez** [comment]
> I like the idea of presenting the spock logging. @teresanunez, since you are the one who developed it, could you do the presentation? I could add a couple of words about the "report" feature of the MacroServer which is somehow related.

@reszelaz, I could say something about what we are already using.

> For 2018, at Alba, we are planning to focus on the 2D detectors and Lima integration in Sardana. Do you think that we could dedicate 5 min per each institute to describe our requirements and needs in this area?

No problem

**Pull request merged**
