### PR TITLE
Adding minutes

### PR DESCRIPTION
**Pull request by teresanunez**

### CODE REVIEW

**Review by daneos — APPROVED** [review]
Fixed some typos and added proposed date for the next meeting.  
@teresanunez do you agree on that date?

**Comment by teresanunez** [comment]
Hi @daneos, many thanks. Yes, the date is perfect, thanks.

**Review by reszelaz — APPROVED** [review]
Very good and detailed!

**Review by julianofjm — APPROVED** [review]
Very good, thanks for the minutes.

**Comment by teresanunez** [comment]
Many thanks. I merge it.

**Pull request merged**
