### PR TITLE
Add agenda of 2019-05-16 meeting

### PR DESCRIPTION
**Pull request by reszelaz**
Please comment. If finally there are no proposals for the presentation, I think we wont be bored - there are a lot of things to discuss about the workshop and docs-camp.

### CODE REVIEW

**Comment by teresanunez** [comment]
I think it is ok like this, thanks. It is important to dedicate time for discussing about the WS and Documentation Camp.

**Comment by amilan** [comment]
Hi,

The agenda looks good. 
For the presentation, I would like to make a short one with a proposal on how we can create Sardana controllers using cookiecutter and the possibilities that it brings to improve the 3rd party repository.

**Comment by reszelaz** [comment]
@amilan I added your presentation to the agenda. Thanks for the proposal!

@daneos do you agree on the agenda? If yes I will merge it and announce it via email.

**Review by daneos — APPROVED** [review]
The agenda looks good, I think it can be merged.
Thanks!

**Comment by reszelaz** [comment]
Great! Merging then and I will send the email invitation.

**Pull request merged**
