### PR TITLE
Agenda for the meeting on 2019-02-14

### PR DESCRIPTION
**Pull request by amilan**
Adding the agenda for the meeting to be held on 2019-02-14 at 14:00h.

### CODE REVIEW

**Comment by amilan** [comment]
Hi,
Here you have a tentative agenda for the next meeting to be held on 2019-02-14.
Please add/modify any topic that you may find interesting.

As an open question: Is there anyone thinking about doing any presentation?

Cheers,
Antonio.

**Comment by reszelaz** [comment]
@amilan  thanks for the agenda!

I would like to give you an update on the SEP2, so I think this should go to the "Overview of current developments" section.

> Is there anyone thinking about doing any presentation?

I was thinking to prepare a presentation on the Bliss project Beacon server - a possiblity to Sardana to store its persistend configuration in YAML files and Redis database. During the ABCDA workshop Matias from ESRF showed me how to use it. I wanted to share it with you.

If we manage to get [sardna-org/sardana#997](https://github.com/sardana-org/sardana/pull/997) accepted before the follow-up meeting maybe we could present this feature? @teresanunez do you feel like presenting this one?

Also since we advanced on #32 and we are now releasing Jan19 milestone we could try to agree the *newsletter* format and eventually redistribute work of the upcoming release newsletter.

**Comment by amilan** [comment]
Hi @reszelaz, 
I have added your point into the agenda.

**Comment by teresanunez** [comment]
Hi @reszelaz, yes, if we integrate #997, I could talk about it at the meeting. No problem. I do not
 promise transparencies, but at least explain what is done.

**Comment by teresanunez** [comment]
I see now that it is already in the agenda as Overview of current developments, also fine for me, so I would say something there.

**Comment by reszelaz** [comment]
> I do not promise transparencies, but at least explain what is done.

I think that better then transparencies would be some live demo, or code snippets on how to use it. Thanks in advance!

**Comment by amilan** [comment]
Hi again, 

I think it's time to merge the agenda 

See you later!

**Pull request merged**
