### PR TITLE
Add minutes from 20180517.

### PR DESCRIPTION
**Pull request by reszelaz**

### CODE REVIEW

**Review by teresanunez — COMMENTED** [review]
Only some details:

- typo in DESY issues:
 " but are a custom solution" -> "but a custom solution"

- Accelertion vs AccelerationTime: we have actually still the Acceleration as AccelerationTime in Sardana

**Review by amilan — APPROVED** [review]

**Comment by amilan** [comment]
Looks OK :+1:

**Review by daneos — APPROVED** [review]
Looks good!

**Comment by reszelaz** [comment]
Merging!

**Pull request merged**
