### PR TITLE
added minutes and LaVue presentation from 20210218

### PR DESCRIPTION
**Pull request by 13bscsaamjad**
- comments are welcomed.

### CODE REVIEW

**Comment by teresanunez** [comment]
Hi Abdullah,
                       many thanks for the minutes. I have a first comment. As Zibi mentioned during the meeting, it would
be nice if the person organizing the next one doesn´t need to read the whole minutes for knowing which points should
be kept. Perhaps you can mark with a ´x´ the points that could be removed and only leave with an empty [ ] the ones that
should be kept. It is only one idea.
                           Best Regards,
                                                 Teresa

**Review by teresanunez — APPROVED** [review]

**Review by cpt-majkel — APPROVED** [review]

**Comment by jkotan** [comment]
Hi,

There were a few questions about LimaCCDs attributes and value_ref scheme supports. Thus,

1) I've just released lavue v2.57.0  where I've added a support for DATA_ARRAY format used in `LimaCCDs.last_image` attribute. So now it should be possible to read images from this attribute via lavue Tango Attribute/Events image sources. Before it was possible to read only `LimaCCDs._video_last_image` with `video_live` set to `true`
2) in lavue v2.56.0 I've added a support for the 'file:/' scheme in the Tango Files image source so in this source you need to set the File attribute with the file:/ url and images should be viewed by lavue (Dir attribute should stay empty in this case).

I've not add a support the `h5file:/` scheme. In order to do it one need to add more widgets to Tango File e.g. with frame number or stacking dimension (which is not provide by the h5file:/ scheme.). So I need more time to do it in a nice way. However,  NeXus Files one can use the NeXus  File image source.

**Comment by jkotan** [comment]
Hi, just to let you know. In Lavue v2.59.0 I 've added support for the `h5cpp:/` scheme in the Tango File image source.

**Comment by reszelaz** [comment]
@jkotan, thanks for joining the meeting and presenting the Lavue and for the post-meeting updates. I will certainly come back to this when we finish with the Jan20 release.

**Review by reszelaz — APPROVED** [review]

**Pull request merged**
